name: RUTA787
favicon: null
layout_spectrum: 0.25145
typography_spectrum: 0.0962
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#00a652'
    - '#565656'
    - '#a4a4a4'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
