analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.007661955896764994
  brandStrength: 0.611111
  lightness: 0.6906249613966793
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#00A652'
    - '#444444'
    - '#A4A7AE'
  rhythmicContrast: 0.2982198903337121
typography_spectrum: 0.5250896
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: RUTA787
